### ISSUE TITLE
Server side crash from Industrial Foregoing, but seems Morph o Tools is to blame

### ISSUE THREAD

**Issue by BedrockLegends** [Vazkii/Morph-o-Tool#55] opened 2020-04-24 14:44 UTC
https://gist.github.com/BedrockLegends/2bc4dbd3320e4c4691ecc874a7d2602b

**Comment by Vazkii** [comment] 2020-04-24 16:36
Dupe of #54

**Closed by Vazkii** 2020-04-24 16:36 UTC

**Comment by BedrockLegends** [comment] 2020-04-27 02:47
yea
